name: ExtraInvisiblePotion
version: '${version}'
main: com.NguyenDevs.extraInvisiblePotion.ExtraInvisiblePotion
api-version: '1.21'
description: Allows using Anvil to combine equipment with Invisible Potions.
author: NguyenDevs
depend: [ProtocolLib]

commands:
  eip:
    description: ExtraInvisiblePotion main command.
    usage: /eip <reload>
    permission: extrainvisiblepotion.admin

permissions:
  extrainvisiblepotion.admin:
    description: Access to /eip admin commands.
    default: op
  extrainvisiblepotion.bypass:
    description: Allows seeing invisible items on other players.
    default: op
  extrainvisiblepotion.use:
    description: Allows using invisible items (wearing them makes them invisible).
    default: true
  extrainvisiblepotion.anvil:
    description: Allows using the invisible anvil crafting feature and shift-click.
    default: true
  extrainvisiblepotion.command.enchant:
    description: Allows using the /eip enchant command.
    default: op
